version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: laravel-app
    ports:
      - "5555:8080"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:gf1WBSPi5rwYXFSwUnLurCkogMRQLZYnVzCuLQfc6U8=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8080

  db:
    image: mysql:8
    container_name: laravel-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbda
